name: Build

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: cd cicd/tests && npm ci

      - name: Build
        run: cd cicd/tests && npm run build
